version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tourism-backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: ./dash
      dockerfile: Dockerfile
    container_name: tourism-frontend
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000/chat
    ports:
      - "8050:8050"
